version: "3.9"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db:/var/lib/postgresql/data
      - ./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"


  server:
    container_name: anti-bruteforce-app
    build: ./
    image: anti-bruteforce-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      SERVER_TYPE: grpc
    links:
      - db
    volumes:
      - './:/src'

volumes:
  db:
    driver: local