// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: bucket_service.proto

package bucketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *Request `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_bucket_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResetBucketRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

type ResetBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResetLogin bool `protobuf:"varint,1,opt,name=resetLogin,proto3" json:"resetLogin,omitempty"`
	ResetIp    bool `protobuf:"varint,2,opt,name=resetIp,proto3" json:"resetIp,omitempty"`
}

func (x *ResetBucketResponse) Reset() {
	*x = ResetBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bucket_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketResponse) ProtoMessage() {}

func (x *ResetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bucket_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketResponse.ProtoReflect.Descriptor instead.
func (*ResetBucketResponse) Descriptor() ([]byte, []int) {
	return file_bucket_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResetBucketResponse) GetResetLogin() bool {
	if x != nil {
		return x.ResetLogin
	}
	return false
}

func (x *ResetBucketResponse) GetResetIp() bool {
	if x != nil {
		return x.ResetIp
	}
	return false
}

var File_bucket_service_proto protoreflect.FileDescriptor

var file_bucket_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x14,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x72, 0x65, 0x73, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x65, 0x74, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x65, 0x74, 0x49, 0x70, 0x32, 0x57, 0x0a, 0x0d, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x26, 0x5a, 0x24, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x61, 0x70, 0x69, 0x2f, 0x62,
	0x75, 0x63, 0x6b, 0x65, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bucket_service_proto_rawDescOnce sync.Once
	file_bucket_service_proto_rawDescData = file_bucket_service_proto_rawDesc
)

func file_bucket_service_proto_rawDescGZIP() []byte {
	file_bucket_service_proto_rawDescOnce.Do(func() {
		file_bucket_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bucket_service_proto_rawDescData)
	})
	return file_bucket_service_proto_rawDescData
}

var file_bucket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bucket_service_proto_goTypes = []interface{}{
	(*ResetBucketRequest)(nil),  // 0: bucket.ResetBucketRequest
	(*ResetBucketResponse)(nil), // 1: bucket.ResetBucketResponse
	(*Request)(nil),             // 2: bucket.Request
}
var file_bucket_service_proto_depIdxs = []int32{
	2, // 0: bucket.ResetBucketRequest.request:type_name -> bucket.Request
	0, // 1: bucket.BucketService.ResetBucket:input_type -> bucket.ResetBucketRequest
	1, // 2: bucket.BucketService.ResetBucket:output_type -> bucket.ResetBucketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bucket_service_proto_init() }
func file_bucket_service_proto_init() {
	if File_bucket_service_proto != nil {
		return
	}
	file_bucket_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bucket_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bucket_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bucket_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bucket_service_proto_goTypes,
		DependencyIndexes: file_bucket_service_proto_depIdxs,
		MessageInfos:      file_bucket_service_proto_msgTypes,
	}.Build()
	File_bucket_service_proto = out.File
	file_bucket_service_proto_rawDesc = nil
	file_bucket_service_proto_goTypes = nil
	file_bucket_service_proto_depIdxs = nil
}
